- name: Variables
  hosts: local
  connection: local
  tasks:
  - name: Print the Variables
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"