- name: install Nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx for RHEL9
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install nginx for Ubuntu
    ansible.builtin.apt:
      name: nginx
      state: installed
    when: ansible_os_family == "Debian"